pipeline {
    agent {
          docker {image "node:16-alpine"}
    }
    stages {
        stage ("First Stage"){
            step{
                sh "node --version"
            }
        }
    }
}