pipeline{
    agent none
    stages{
        stage("Frontend"){
            
                agent {
                    docker { image 'maven:3.8.1-adoptopenjdk-11' }
                 }
      steps {
        sh 'mvn --version'
      }
            }

            stage("Backend"){
            
                agent{
                    docker {image "node:16-alpine"}
                }
                step{
                sh "node --version"
            }
        }
        }
    }
